/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        /* Concrete scale */
        cement: {
          50:  '#F7F6F4',
          100: '#EDEAE5',
          200: '#D9D4CC',
          300: '#C2BAB0',
          400: '#A8A098',
          500: '#8B8278',
          600: '#6E6560',
          700: '#514A45',
          800: '#352F2B',
          900: '#1C1714',
          950: '#0E0C0A',
        },
        /* Signaling colors */
        getto:  'var(--getto)',
        hazard: 'var(--hazard)',
        rebar:  'var(--rebar)',
        steel:  'var(--steel)',

        /* Surfaces */
        bg:        'var(--bg)',
        'surface-1': 'var(--surface-1)',
        'surface-2': 'var(--surface-2)',
        hairline:  'var(--hairline)',

        /* Text */
        'text-1': 'var(--text-1)',
        'text-2': 'var(--text-2)',
        'text-3': 'var(--text-3)',

        /* Backward-compat aliases */
        app:      'var(--c-app)',
        section:  'var(--c-section)',
        card:     'var(--c-card)',
        ink:      'var(--c-ink)',
        'ink-2':  'var(--c-ink-2)',
        'ink-3':  'var(--c-ink-3)',
        line:     'var(--c-line)',
        divider:  'var(--c-divider)',
        activity: 'var(--c-activity)',
        habit:    'var(--c-habit)',
        project:  'var(--c-project)',
        journal:  'var(--c-journal)',
        finance:  'var(--c-finance)',
        ore:      'var(--c-ore)',
        note:     'var(--c-note)',
        'wd-lavorativa': 'var(--c-wd-lavorativa)',
        'wd-festiva':    'var(--c-wd-festiva)',
        'wd-malattia':   'var(--c-wd-malattia)',
        'wd-infortunio': 'var(--c-wd-infortunio)',
        'wd-ferie':      'var(--c-wd-ferie)',
        'wd-permesso':   'var(--c-wd-permesso)',
        success:      'var(--c-success)',
        warning:      'var(--c-warning)',
        danger:       'var(--c-danger)',
        primary:      'var(--c-primary)',
        'on-primary': 'var(--c-on-primary)',
        'primary-border': 'var(--c-primary-border)',
        'accent-soft':     'var(--c-accent-soft-bg)',
        'accent-soft-ink': 'var(--c-accent-soft-ink)',
      },
      borderRadius: {
        card: '14px',
        btn:  '10px',
        sm:   '10px',
        md:   '14px',
        lg:   '18px',
        xl:   '22px',
      },
      boxShadow: {
        card:       'var(--slab-base)',
        'card-md':  'var(--slab-raised)',
        'card-glass': 'var(--slab-glass)',
        slab:       'var(--slab-base)',
        'slab-raised': 'var(--slab-raised)',
        'slab-glass':  'var(--slab-glass)',
        sheet:      '0 -8px 40px rgba(0,0,0,0.18)',
        'glow-sm':  '0 4px 16px rgba(245,81,0,0.32)',
        'glow-md':  '0 6px 24px rgba(245,81,0,0.40)',
        'glow-rebar': '0 4px 14px rgba(31,155,78,0.32)',
        'glow-steel': '0 4px 14px rgba(26,111,202,0.32)',
      },
      fontFamily: {
        sans:    ['"Geist Variable"', '-apple-system', 'BlinkMacSystemFont', 'system-ui', 'sans-serif'],
        mono:    ['"Geist Mono Variable"', '"Geist Mono"', 'ui-monospace', '"SF Mono"', 'Menlo', 'monospace'],
        display: ['"Geist Variable"', '-apple-system', 'BlinkMacSystemFont', 'system-ui', 'sans-serif'],
      },
      spacing: {
        'safe-top':    'env(safe-area-inset-top)',
        'safe-bottom': 'env(safe-area-inset-bottom)',
        'safe-left':   'env(safe-area-inset-left)',
        'safe-right':  'env(safe-area-inset-right)',
      },
      transitionDuration: {
        150: '150ms',
        250: '250ms',
      },
    },
  },
  plugins: [],
};
