export interface ArtigianoDirectory {
  id: string;
  nome: string;
  provincia: string;
  citta: string;
  specializzazioni: string[];
  esperienzaAnni: number;
  telefono?: string;
  descrizione: string;
  valutazione: 1 | 2 | 3 | 4 | 5;
}

export const DIRECTORY_VENETO: ArtigianoDirectory[] = [
  // Treviso (TV) — 5 entries
  {
    id: 'dir-001',
    nome: 'Fabbri Pavimenti s.r.l.',
    provincia: 'TV',
    citta: 'Treviso',
    specializzazioni: ['Gettista', 'Levigatore'],
    esperienzaAnni: 18,
    telefono: '0422 123456',
    descrizione: 'Specializzati in pavimenti industriali e levigatura di precisione. Getti su grande superficie.',
    valutazione: 5,
  },
  {
    id: 'dir-002',
    nome: 'Marco Zanchin',
    provincia: 'TV',
    citta: 'Montebelluna',
    specializzazioni: ['Posatore', 'Carpentiere'],
    esperienzaAnni: 12,
    telefono: '347 8901234',
    descrizione: 'Posatore indipendente con esperienza in residenziale e garage. Lavori curati e puntuali.',
    valutazione: 4,
  },
  {
    id: 'dir-003',
    nome: 'Costruzioni Bortolot s.n.c.',
    provincia: 'TV',
    citta: 'Vittorio Veneto',
    specializzazioni: ['Gettista', 'Ferraiolo', 'Carpentiere'],
    esperienzaAnni: 25,
    telefono: '0438 654321',
    descrizione: 'Impresa storica del trevigiano, capannoni industriali e pavimentazioni su misura.',
    valutazione: 5,
  },
  {
    id: 'dir-004',
    nome: 'Luca Gasperin',
    provincia: 'TV',
    citta: 'Conegliano',
    specializzazioni: ['Levigatore'],
    esperienzaAnni: 8,
    telefono: '346 5678901',
    descrizione: 'Levigatura e lucidatura cemento. Referenziato in appartamenti e showroom moderni.',
    valutazione: 4,
  },
  {
    id: 'dir-005',
    nome: 'Pavimenti Tonon',
    provincia: 'TV',
    citta: 'Oderzo',
    specializzazioni: ['Posatore', 'Gettista'],
    esperienzaAnni: 15,
    telefono: '0422 987654',
    descrizione: 'Dal 2009 al servizio di privati e imprese nel trevigiano. Preventivi gratuiti entro 24h.',
    valutazione: 4,
  },

  // Venezia (VE) — 5 entries
  {
    id: 'dir-006',
    nome: 'Adriatico Calcestruzzi s.r.l.',
    provincia: 'VE',
    citta: 'Mestre',
    specializzazioni: ['Gettista', 'Levigatore', 'Ferraiolo'],
    esperienzaAnni: 22,
    telefono: '041 2345678',
    descrizione: 'Grande impresa veneziana per getti conto terzi, levigatura e ripristino superfici.',
    valutazione: 5,
  },
  {
    id: 'dir-007',
    nome: 'Stefano Molon',
    provincia: 'VE',
    citta: 'Mirano',
    specializzazioni: ['Posatore'],
    esperienzaAnni: 10,
    telefono: '338 2345678',
    descrizione: 'Posatore di fiducia per residenziale. Rifiniture di qualità, rispetto dei tempi.',
    valutazione: 4,
  },
  {
    id: 'dir-008',
    nome: 'Edil Marcon & Figli',
    provincia: 'VE',
    citta: 'Portogruaro',
    specializzazioni: ['Carpentiere', 'Gettista'],
    esperienzaAnni: 30,
    telefono: '0421 543210',
    descrizione: 'Tre generazioni di esperienza nel cemento. Specializzati in opere strutturali e getti complessi.',
    valutazione: 5,
  },
  {
    id: 'dir-009',
    nome: 'Davide Ruzzante',
    provincia: 'VE',
    citta: 'Spinea',
    specializzazioni: ['Levigatore'],
    esperienzaAnni: 7,
    telefono: '349 3456789',
    descrizione: 'Levigatura e trattamento superfici cementizie per privati. Attrezzatura professionale.',
    valutazione: 3,
  },
  {
    id: 'dir-010',
    nome: 'Dal Borgo Pavimenti',
    provincia: 'VE',
    citta: 'Dolo',
    specializzazioni: ['Posatore', 'Levigatore'],
    esperienzaAnni: 14,
    telefono: '041 7654321',
    descrizione: 'Posatura e finitura pavimenti continui in cemento. Referenze in ville e spazi commerciali.',
    valutazione: 4,
  },

  // Padova (PD) — 5 entries
  {
    id: 'dir-011',
    nome: 'Euganea Calcestruzzi s.r.l.',
    provincia: 'PD',
    citta: 'Padova',
    specializzazioni: ['Gettista', 'Ferraiolo', 'Carpentiere'],
    esperienzaAnni: 20,
    telefono: '049 8765432',
    descrizione: 'Impresa strutturata per opere civili e industriali nella provincia di Padova.',
    valutazione: 5,
  },
  {
    id: 'dir-012',
    nome: 'Nicola Baldan',
    provincia: 'PD',
    citta: 'Cittadella',
    specializzazioni: ['Posatore'],
    esperienzaAnni: 9,
    telefono: '340 9876543',
    descrizione: 'Artigiano indipendente. Pavimenti in cemento lisciato per abitazioni private.',
    valutazione: 4,
  },
  {
    id: 'dir-013',
    nome: 'Fratelli Calore',
    provincia: 'PD',
    citta: 'Este',
    specializzazioni: ['Gettista', 'Levigatore'],
    esperienzaAnni: 17,
    telefono: '0429 876543',
    descrizione: 'Fratelli specializzati in getti industriali e levigatura di precisione nel basso padovano.',
    valutazione: 4,
  },
  {
    id: 'dir-014',
    nome: 'Alberto Pinton',
    provincia: 'PD',
    citta: 'Abano Terme',
    specializzazioni: ['Carpentiere', 'Ferraiolo'],
    esperienzaAnni: 11,
    telefono: '339 7654321',
    descrizione: 'Carpentiere e ferraiolo per opere in calcestruzzo armato. Disponibile per subappalti.',
    valutazione: 3,
  },
  {
    id: 'dir-015',
    nome: 'Pavimenti Borin',
    provincia: 'PD',
    citta: 'Camposampiero',
    specializzazioni: ['Posatore', 'Levigatore'],
    esperienzaAnni: 13,
    telefono: '049 5432109',
    descrizione: 'Pavimentazioni residenziali e commerciali. Pronto intervento per rifacimenti urgenti.',
    valutazione: 4,
  },

  // Vicenza (VI) — 5 entries
  {
    id: 'dir-016',
    nome: 'Palladio Costruzioni s.r.l.',
    provincia: 'VI',
    citta: 'Vicenza',
    specializzazioni: ['Gettista', 'Carpentiere', 'Ferraiolo'],
    esperienzaAnni: 28,
    telefono: '0444 234567',
    descrizione: 'Impresa storica vicentina per grandi opere civili. Magazzini, capannoni e infrastrutture.',
    valutazione: 5,
  },
  {
    id: 'dir-017',
    nome: 'Giovanni Segato',
    provincia: 'VI',
    citta: 'Schio',
    specializzazioni: ['Posatore'],
    esperienzaAnni: 6,
    telefono: '333 1234567',
    descrizione: 'Giovane posatore con ottima manualità. Referenze in abitazioni private e garage.',
    valutazione: 3,
  },
  {
    id: 'dir-018',
    nome: 'Dalla Pozza & Associati',
    provincia: 'VI',
    citta: 'Bassano del Grappa',
    specializzazioni: ['Gettista', 'Levigatore'],
    esperienzaAnni: 16,
    telefono: '0424 567890',
    descrizione: 'Getti di qualità e levigatura in tutto il bassanese. Partner affidabile per imprese edili.',
    valutazione: 4,
  },
  {
    id: 'dir-019',
    nome: 'Renato Sartori',
    provincia: 'VI',
    citta: 'Thiene',
    specializzazioni: ['Ferraiolo', 'Carpentiere'],
    esperienzaAnni: 21,
    telefono: '0445 678901',
    descrizione: 'Esperto ferraiolo per strutture in cemento armato. Puntuale e preciso.',
    valutazione: 4,
  },
  {
    id: 'dir-020',
    nome: 'Cementi Bertin',
    provincia: 'VI',
    citta: 'Lonigo',
    specializzazioni: ['Posatore', 'Gettista'],
    esperienzaAnni: 19,
    telefono: '0444 789012',
    descrizione: 'Azienda a conduzione familiare. Posatura e getti per privati e piccole imprese.',
    valutazione: 4,
  },

  // Verona (VR) — 5 entries
  {
    id: 'dir-021',
    nome: 'Arena Calcestruzzi s.r.l.',
    provincia: 'VR',
    citta: 'Verona',
    specializzazioni: ['Gettista', 'Levigatore', 'Ferraiolo'],
    esperienzaAnni: 24,
    telefono: '045 3456789',
    descrizione: 'Leader veronese nei pavimenti industriali. Certificati ISO, grandi superfici.',
    valutazione: 5,
  },
  {
    id: 'dir-022',
    nome: 'Filippo Consolaro',
    provincia: 'VR',
    citta: 'Legnago',
    specializzazioni: ['Posatore'],
    esperienzaAnni: 8,
    telefono: '0442 678901',
    descrizione: 'Posatore affidabile nel veronese. Specializzato in pavimenti residenziali e terrazze.',
    valutazione: 4,
  },
  {
    id: 'dir-023',
    nome: 'Adige Pavimenti s.n.c.',
    provincia: 'VR',
    citta: 'San Bonifacio',
    specializzazioni: ['Posatore', 'Levigatore'],
    esperienzaAnni: 12,
    telefono: '045 9012345',
    descrizione: 'Duo specializzato in posatura e finitura. Ottimi risultati in showroom e negozi.',
    valutazione: 4,
  },
  {
    id: 'dir-024',
    nome: 'Silvio Marangoni',
    provincia: 'VR',
    citta: 'Villafranca di Verona',
    specializzazioni: ['Carpentiere', 'Gettista'],
    esperienzaAnni: 15,
    telefono: '342 6789012',
    descrizione: 'Carpentiere e gettista con esperienza in zone industriali. Disponibile da subito.',
    valutazione: 3,
  },

  // Belluno (BL) — 1 entry
  {
    id: 'dir-025',
    nome: 'Dolomiti Calcestruzzi s.r.l.',
    provincia: 'BL',
    citta: 'Belluno',
    specializzazioni: ['Gettista', 'Ferraiolo'],
    esperienzaAnni: 20,
    telefono: '0437 234567',
    descrizione: 'Specializzati in getti in quota e zone di montagna. Attrezzatura per condizioni difficili.',
    valutazione: 4,
  },

  // Rovigo (RO) — 1 entry
  {
    id: 'dir-026',
    nome: 'Delta Pavimenti',
    provincia: 'RO',
    citta: 'Rovigo',
    specializzazioni: ['Posatore', 'Levigatore'],
    esperienzaAnni: 11,
    telefono: '0425 345678',
    descrizione: 'Pavimentazioni in cemento per il polesine. Privati, agricoltura e piccola industria.',
    valutazione: 3,
  },
];
