import { readdirSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import puppeteer from 'puppeteer';
const DIR = resolve('/home/user/vita/store/onboarding');
const files = readdirSync(DIR).filter(f=>f.endsWith('.png')&&!f.startsWith('_')).sort();
const cards = files.map(f=>{const b=readFileSync(resolve(DIR,f)).toString('base64');return `<img src="data:image/png;base64,${b}"/>`}).join('');
const html=`<!doctype html><meta charset=utf-8><body style="margin:0;background:#f8f1e6;padding:24px"><div style="display:grid;grid-template-columns:repeat(4,1fr);gap:16px">${cards.replace(/<img/g,'<img style="width:100%;border-radius:20px;box-shadow:0 8px 24px rgba(83,52,20,.14)"')}</div></body>`;
const br=await puppeteer.launch({args:['--no-sandbox','--disable-setuid-sandbox']});
const p=await br.newPage();await p.setViewport({width:1700,height:1000,deviceScaleFactor:1});
await p.setContent(html,{waitUntil:'networkidle0'});
await p.screenshot({path:resolve(DIR,'_sheet.png'),fullPage:true});
await br.close();console.log('ok');
